### ISSUE TITLE
pkg/hub/submarineragent UTs fail in some cases

### ISSUE THREAD

**Issue by skitt** [stolostron/submariner-addon#455] opened 2022-07-26 09:07 UTC
Since #451 was merged, we’re seeing failures of the `pkg/hub/submarineragent` UT, for example on #454 — the failures also happen on `main` so they’re not related to the changes in #454.

To reproduce, force a test run with no cache; this is highly likely to fail:

```
go test -mod=vendor -count=1 -race ./pkg/hub/submarineragent
```

The likelihood of failure reduces if the tests are constrained to a single CPU:

```
taskset -c 0 go test -mod=vendor -count=1 -race ./pkg/hub/submarineragent
```

It’s difficult to determine the actual cause of the failure, but it appears to be a panic during teardown because of an unexpected call to `PrepareSubmarinerClusterEnv()`.

**Comment by mkolesnik** [comment] 2022-07-26 13:53
I've been bashing my head on this for half a day, but genereally it's some kind of race condition.

The main culprit is this removal [1] which I restored with a note in #456 

[1] https://github.com/stolostron/submariner-addon/pull/451/files#diff-04651272ceeb407cc687aced0289d1503d9c3ca154fff47d7a0b4af8dee12ddcL302

**Comment by mkolesnik** [comment] 2022-07-26 13:58
> It’s difficult to determine the actual cause of the failure, but it appears to be a panic during teardown because of an unexpected call to PrepareSubmarinerClusterEnv().

Yes basically it's that, and it's shit to debug because the panic aborts everything in the middle of the run, making it quite impossible to know which exact test failed.

It can also be easily recreated by running tests slower, e.g. with `-v` flag:
```
make test-unit GO_TEST_PACKAGES="github.com/stolostron/submariner-addon/pkg/hub/submarineragent" GO_TEST_FLAGS="-v"
```

**Comment by tpantelis** [comment] 2022-07-26 14:12
> > It’s difficult to determine the actual cause of the failure, but it appears to be a panic during teardown because of an unexpected call to PrepareSubmarinerClusterEnv().

We need GingkoRecover as is done in other tests. With that added (locally), it fails in this test case:

```
Controller
/home/tompantelis/go/src/github.com/stolostron/submariner-addon/pkg/hub/submarineragent/controller_test.go:61
  when the SubmarinerConfig is created after the submariner ManifestWork is deployed [JustBeforeEach]
  /home/tompantelis/go/src/github.com/stolostron/submariner-addon/pkg/hub/submarineragent/controller_test.go:177                                                                                                            
    and the platform is set to AWS
    /home/tompantelis/go/src/github.com/stolostron/submariner-addon/pkg/hub/submarineragent/controller_test.go:190                                                                                                          
      should invoke cloud prepare
      /home/tompantelis/go/src/github.com/stolostron/submariner-addon/pkg/hub/submarineragent/controller_test.go:202    
      
      Unexpected call to *fake.MockProvider.PrepareSubmarinerClusterEnv([]) at /home/tompantelis/go/src/github.com/stolostron/submariner-addon/pkg/hub/submarineragent/controller.go:390 because: there are no expected calls of the method "PrepareSubmarinerClusterEnv" for that receiver                             
```

**Comment by tpantelis** [comment] 2022-07-26 15:06
So the problem is actually with the prior test:

```
Controller when the SubmarinerConfig is created after the submariner ManifestWork is deployed 
  should update the ManifestWorks
  /home/tompantelis/go/src/github.com/stolostron/submariner-addon/pkg/hub/submarineragent/controller_test.go:184      
```                                                                                       

The test doesn't set the platform so `isSpokePrepared`: 

```Go
func isSpokePrepared(cloudName string) bool {
	if cloudName == "GCP" || cloudName == "OpenStack" || cloudName == "Azure" {
		return true
	}

	return false
}
```

returns false so the controller tries to invoke `PrepareSubmarinerClusterEnv` but the test hasn't set up the expectation. The failure can happen sporadically if it runs long enough for a tangential `SubmarinerConfig` update to be processed after the finalizer is added. This was inadvertently introduced by the fix in https://github.com/stolostron/submariner-addon/pull/451.  

So we can fix it by specifically setting the platform to "GCP" so `PrepareSubmarinerClusterEnv` is correctly elided. #453 also indirectly fixes the issue by only invoking cloud prepare on AWS. I think we should get #453  reviewed and merged. Post 2.6, once we move AWS cloud prepare to the spoke, this code goes away.

**Closed** 2022-07-26 16:19 UTC
